const tabLevel = document.querySelector('.tabLevel')
const modeEN = document.querySelector('.EN')
const modeTH = document.querySelector('.TH')
const Ranking = document.querySelector('.rank')
const show = document.querySelector('.show')
const input = document.querySelector('.input')
const anser = document.querySelector('.anser')
const submit = document.querySelector('.submit')

const data = [
    {eng:'a lot',thai:'มาก'},
    {eng:'able',thai:'สามารถ'},
    {eng:'about',thai:['เกี่ยวกับ','ประมาณ' ]},
    {eng:'above',thai:'เหนือ'},
    {eng:'actually',thai:['จริงๆแล้ว','จริงๆเเล้ว']},

    {eng:'add',thai:['บวก', 'เพิ่ม']},
    {eng:'afraid',thai:'กลัว'},
    {eng:'after',thai:'หลังจาก'},
    {eng:'again',thai:'อีกครั้ง'},
    {eng:'against',thai:['ต่อต้าน', 'พิง']},

    {eng:'age',thai:'อายุ'},
    {eng:'ago',thai:'ที่ผ่านมา'},
    {eng:'agree',thai:'เห็นด้วย'},
    {eng:'air',thai:'อากาศ'},
    {eng:'all',thai:'ทั้งหมด'},

    {eng:'allow',thai:'อนุญาต'},
    {eng:'also',thai:['ด้วย', 'เช่นกัน']},
    {eng:'always',thai:'ตลอด'},
    {eng:'am',thai:['เป็น', 'อยู่', 'คือ']},
    {eng:'among',thai:'ระหว่าง'},

    {eng:'an',thai:'หนึ่ง'},
    {eng:'and',thai:'และ'},
    {eng:'anger',thai:'ความโกรธ'},
    {eng:'angle',thai:'มุม'},
    {eng:'animal',thai:'สัตว์'},

    {eng:'answer',thai:['ตอบ', 'คำตอบ']},
    {eng:'aunt',thai:'ป้า'},
    {eng:'any',thai:['ใดๆ', 'เลย']},
    {eng:'appear',thai:'ปรากฏ'},
    {eng:'apple',thai:'แอปเปิ้ล'},

    {eng:'area',thai:'พื้นที่'},
    {eng:'arm',thai:'แขน'},
    {eng:'arrange',thai:'จัดแจง'},
    {eng:'arrive',thai:'มาถึง'},
    {eng:'art',thai:'ศิลปะ'},

    {eng:'as',thai:['ขณะที่', 'ราวกับ', 'เนื่องจาก']},
    {eng:'ask',thai:'ถาม'},
    {eng:'at',thai:'ที่'},
    {eng:'baby',thai:['เด็ก', 'ที่รัก']},
    {eng:'back',thai:'หลัง'},

    {eng:'bad',thai:'เลว'},
    {eng:'ball',thai:'ลูกบอล'},
    {eng:'banana',thai:'กล้วย'},
    {eng:'band',thai:'วงดนตรี'},
    {eng:'bank',thai:'ธนาคาร'},

    {eng:'bar',thai:['ร้านเหล้า', 'แท่ง']},
    {eng:'barber',thai:'ช่างตัดผม'},
    {eng:'base',thai:'ฐาน'},
    {eng:'basic',thai:'พื้นฐาน'},
    {eng:'basket',thai:'ตะกร้า'},

    {eng:'bat',thai:'ค้างคาว'},
    {eng:'be',thai:['เป็น', 'อยู่', 'คือ']},
    {eng:'beach',thai:'ชายหาด'},
    {eng:'bear',thai:'หมี'},
    {eng:'beat',thai:['ตี', 'เอาชนะ']},
    {eng:'beautiful',thai:'สวย'},
    {eng:'beauty',thai:'ความงาม'},
    {eng:'because',thai:'เพราะว่า'},
    {eng:'become',thai:'กลายเป็น'},
    {eng:'bed',thai:'เตียง'},
    {eng:'beer',thai:'เบียร์'},
    {eng:'before',thai:'ก่อน'},
    {eng:'begin',thai:'เริ่ม'},
    {eng:'behind',thai:'หลัง'},
    {eng:'believe',thai:'เชื่อ'},
    {eng:'bell',thai:'กระดิ่ง'},
    {eng:'below',thai:'ใต้'},
    {eng:'beside',thai:'ข้างๆ'},
    {eng:'best',thai:'ดีที่สุด'},
    {eng:'better',thai:'ดีกว่า'},
    {eng:'between',thai:'ระหว่าง'},
    {eng:'big',thai:'ใหญ่'},
    {eng:'bike',thai:'จักรยาน'},
    {eng:'bird',thai:'นก'},
    {eng:'bit',thai:'ส่วน'},
    {eng:'bitter',thai:'ขม'},
    {eng:'black',thai:'ดำ'},
    {eng:'block',thai:'ช่วงตึก'},
    {eng:'blood',thai:'เลือด'},
    {eng:'blow',thai:['พัด', 'เป่า']},
    {eng:'blue',thai:'สีฟ้า'},
    {eng:'board',thai:['กระดาน', 'กรรมการ']},
    {eng:'boat',thai:'เรือ'},
    {eng:'body',thai:'ร่างกาย'},
    {eng:'bone',thai:'กระดูก'},
    {eng:'book',thai:'หนังสือ'},
    {eng:'boring',thai:'น่าเบื่อ'},
    {eng:'both',thai:'ทั้งคู่'},
    {eng:'bottom',thai:'ก้น'},
    {eng:'box',thai:'กล่อง'},
    {eng:'boy',thai:'เด็กชาย'},
    {eng:'branch',thai:['สาขา', 'กิ่ง']},
    {eng:'bread',thai:'ขนมปัง'},
    {eng:'break',thai:'หยุด'},
    {eng:'bright',thai:['สว่าง', 'ฉลาด']},
    {eng:'bring',thai:'นำมา'},
    {eng:'broad',thai:'กว้าง'},
    {eng:'brother',thai:'พี่ชาย'},
    {eng:'brown',thai:'สีน้ำตาล'},
    {eng:'build',thai:'สร้าง'},
    {eng:'burn',thai:'เผา'},
    {eng:'bury',thai:'ฝัง'},
    {eng:'bus',thai:'รถบัส'},
    {eng:'but',thai:'แต่'},
    {eng:'butter',thai:'เนย'},
    {eng:'buy',thai:'ซื้อ'},
    {eng:'by',thai:'โดย'},
    {eng:'cake',thai:'ขนมเค้ก'},
    {eng:'call',thai:['เรียก', 'โทร']},
    {eng:'camp',thai:'แคมป์'},
    {eng:'can',thai:['สามารถ', ' กระป๋อง']},
    {eng:'canal',thai:'คลอง'},
    {eng:'capital',thai:'เมืองหลวง'},
    {eng:'captain',thai:'กัปตัน'},
    {eng:'car',thai:'รถยนต์'},
    {eng:'card',thai:'การ์ด'},
    {eng:'care',thai:'ห่วงใย'},
    {eng:'carry',thai:'ถือ'},
    {eng:'case',thai:'กล่อง'},
    {eng:'cat',thai:'แมว'},
    {eng:'catch',thai:'จับ'},
    {eng:'cause',thai:'สาเหตุ'},
    {eng:'center',thai:'ศูนย์กลาง'},
    {eng:'century',thai:'ศตวรรษ'},
    {eng:'certain',thai:'แน่นอน'},
    {eng:'chair',thai:'เก้าอี้'},
    {eng:'chance',thai:'โอกาส'},
    {eng:'change',thai:'เปลี่ยน'},
    {eng:'character',thai:'บุคลิกลักษณะ'},
    {eng:'charge',thai:'คิดราคา'},
    {eng:'chart',thai:'ตาราง'},
    {eng:'cheap',thai:'ราคาถูก'},
    {eng:'check',thai:'ตรวจสอบ'},
    {eng:'chick',thai:'ลูกไก่'},
    {eng:'chief',thai:['หัวหน้า', 'สำคัญ']},
    {eng:'child',thai:'เด็ก'},
    {eng:'children',thai:'เด็กๆ'},
    {eng:'choose',thai:'เลือก'},
    {eng:'circle',thai:'วงกลม'},
    {eng:'city',thai:'เมือง'},
    {eng:'claim',thai:'อ้าง'},
    {eng:'class',thai:'ห้องเรียน'},
    {eng:'clean',thai:['สะอาด', 'ทำความสะอาด']},
    {eng:'clear',thai:'ชัดเจน'},
    {eng:'clever',thai:'ฉลาด'},
    {eng:'climb',thai:'ปีน'},
    {eng:'clock',thai:'นาฬิกา'},
    {eng:'close',thai:'ปิด'},
    {eng:'clothes',thai:'เสื้อผ้า'},
    {eng:'cloud',thai:'เมฆ'},
    {eng:'coast',thai:'ฝั่ง'},
    {eng:'coat',thai:'เสื้อคลุม'},
    {eng:'coffee',thai:'กาแฟ'},
    {eng:'cold',thai:'หนาว'},
    {eng:'collect',thai:['สะสม', 'รวบรวม']},
    {eng:'color',thai:'สี'},
    {eng:'column',thai:['คอลัมน์', 'แถวแนวนอน']},
    {eng:'come',thai:'มา'},
    {eng:'common',thai:'ธรรมดา'},
    {eng:'compare',thai:'เปรียบเทียบ'},
    {eng:'complete',thai:'สมบูรณ์'},
    {eng:'condition',thai:'สภาวะ'},
    {eng:'connect',thai:'เชื่อมต่อ'},
    {eng:'consider',thai:'พิจารณา'},
    {eng:'contain',thai:'บรรจุ'},
    {eng:'continent',thai:'ทวีป'},
    {eng:'continue',thai:'ดำเนินการต่อ'},
    {eng:'control',thai:'ควบคุม'},
    {eng:'cook',thai:'พ่อครัว'},
    {eng:'cool',thai:'เย็น'},
    {eng:'copy',thai:'คัดลอก'},
    {eng:'corn',thai:'ข้าวโพด'},
    {eng:'corner',thai:'มุม'},
    {eng:'correct',thai:'ถูกต้อง'},
    {eng:'cost',thai:'มีราคา'},
    {eng:'cotton',thai:'ผ้าฝ้าย'},
    {eng:'could',thai:'สามารถ'},
    {eng:'count',thai:'นับ'},
    {eng:'country',thai:'ประเทศ'},
    {eng:'course',thai:'หลักสูตร'},
    {eng:'cover',thai:'คุม'},
    {eng:'cow',thai:'วัว'},
    {eng:'create',thai:'สร้างสรรค์'},
    {eng:'crop',thai:'ผลผลิต'},
    {eng:'cross',thai:'ข้าม'},
    {eng:'crowd',thai:'ผู้คน'},
    {eng:'cry',thai:'ร้องให้'},
    {eng:'current',thai:'ปัจจุบัน'},
    {eng:'cut',thai:'ตัด'},
    {eng:'dad',thai:'พ่อ'},
    {eng:'dance',thai:'เต้น'},
    {eng:'danger',thai:'อันตราย'},
    {eng:'dark',thai:'มืด'},
    {eng:'daughter',thai:'ลูกสาว'},
    {eng:'day',thai:'วัน'},
    {eng:'deal',thai:'ข้อตกลง'},
    {eng:'dear',thai:'ที่รัก'},
    {eng:'death',thai:'ความตาย'},
    {eng:'decide',thai:'ตัดสินใจ'},
    {eng:'deep',thai:'ลึก'},
    {eng:'degree',thai:'ระดับ'},
    {eng:'dentist',thai:'หมอฟัน'},
    {eng:'depend',thai:'ขึ้นอยู่กัน'},
    {eng:'describe',thai:'บรรยาย'},
    {eng:'desert',thai:'ทะเลทราย'},
    {eng:'design',thai:'ออกแบบ'},
    {eng:'desk',thai:'โต๊ะ'},
    {eng:'determine',thai:'ตัดสินใจ'},
    {eng:'develop',thai:'พัฒนา'},
    {eng:'dictionary',thai:'พจนานุกรม'},
    {eng:'die',thai:'ตาย'},
    {eng:'differ',thai:'แตกต่าง'},
    {eng:'difficult',thai:'ยาก'},
    {eng:'diligent',thai:'ขยัน'},
    {eng:'direct',thai:'โดยตรง'},
    {eng:'dirty',thai:'สกปรก'},
    {eng:'discuss',thai:'อภิปราย'},
    {eng:'distance',thai:'ระยะทาง'},
    {eng:'divide',thai:'แบ่ง'},
    {eng:'division',thai:'แผนก'},
    {eng:'do',thai:'ทำ'},
    {eng:'doctor',thai:'หมอ'},
    {eng:'dog',thai:'สุนัข'},
    {eng:'dollar',thai:'ดอลลาร์'},
    {eng:'door',thai:'ประตู'},
    {eng:'double',thai:['คู่', 'สองเท่า']},
    {eng:'down',thai:'ลง'},
    {eng:'draw',thai:'วาด'},
    {eng:'dream',thai:'ฝัน'},
    {eng:'dress',thai:'ชุด'},
    {eng:'drink',thai:'ดื่ม'},
    {eng:'drive',thai:'ขับ'},
    {eng:'drop',thai:'หยดน้ำ'},
    {eng:'dry',thai:'แห้ง'},
    {eng:'duck',thai:'เป็น'},
    {eng:'during',thai:'ระหว่าง'},
    {eng:'each',thai:'แต่ละ'},
    {eng:'ear',thai:'หู'},
    {eng:'early',thai:'แต่เช้า'},
    {eng:'earth',thai:'โลก'},
    {eng:'ease',thai:'ผ่อนปรน'},
    {eng:'east',thai:'ทิศตะวันออก'},
    {eng:'easy',thai:'ง่าย'},
    {eng:'eat',thai:'กิน'},
    {eng:'edge',thai:'ขอบ'},
    {eng:'education',thai:'การศึกษา'},
    {eng:'effect',thai:'ผลกระทบ'},
    {eng:'egg',thai:'ไข่'},
    {eng:'eight',thai:'แปด'},
    {eng:'electric',thai:'เกี่ยวกับไฟฟ้า'},
    {eng:'electricity',thai:'ไฟฟ้า'},
    {eng:'else',thai:'อื่น'},
    {eng:'empty',thai:'ว่างเปล่า'},
    {eng:'end',thai:'จบ'},
    {eng:'enemy',thai:'ศัตรู'},
    {eng:'energy',thai:'พลังงาน'},
    {eng:'engine',thai:'เครื่องยนต์'},
    {eng:'enough',thai:'พอ'},
    {eng:'enter',thai:'เข้า'},
    {eng:'equal',thai:'เท่ากัน'},
    {eng:'especially',thai:'โดยเฉพาะ'},
    {eng:'even',thai:'แม้ว่า'},
    {eng:'evening',thai:'ตอนค่ำ'},
    {eng:'event',thai:'เหตการณ์'},
    {eng:'ever',thai:'เคย'},
    {eng:'every',thai:'ทุกๆ'},
    {eng:'exact',thai:'ที่แท้จริง'},
    {eng:'example',thai:'ตัวอย่าง'},
    {eng:'except',thai:'ยกเว้น'},
    {eng:'exercise',thai:'การออกกำลังกาย'},
    {eng:'expect',thai:'คาดหมาย'},
    {eng:'expensive',thai:'ราคาแพง'},
    {eng:'experience',thai:'ประสบการณ์'},
    {eng:'excellent',thai:'ยอดเยี่ยม'},
    {eng:'face',thai:'หน้า'},
    {eng:'fact',thai:'ข้อเท็จจริง'},
    {eng:'fair',thai:'ยุติธรรม'},
    {eng:'fall',thai:'ตก'},
    {eng:'family',thai:'ครอบครัว'},
    {eng:'famous',thai:'มีชื่อเสียง'},
    {eng:'far',thai:'ไกล'},
    {eng:'farm',thai:'ฟาร์ม'},
    {eng:'farmer',thai:'เกษตรกร'},
    {eng:'fast',thai:'เร็ว'},
    {eng:'fat',thai:'อ้วน'},
    {eng:'father',thai:'พ่อ'},
    {eng:'favorite',thai:'ที่ชื่นชอบ'},
    {eng:'fear',thai:'กลัว'},
    {eng:'feather',thai:'ขน'},
    {eng:'feed',thai:'ป้อนอาหาร'},
    {eng:'feel',thai:'รู้สึก'},
    {eng:'feet',thai:'เท้า'},
    {eng:'few',thai:'สองสาม'},
    {eng:'field',thai:'ทุ่ง'},
    {eng:'fight',thai:'ต่อสู้'},
    {eng:'figure',thai:'รูปร่าง'},
    {eng:'fill',thai:'เติม'},
    {eng:'final',thai:'สุดท้าย'},
    {eng:'find',thai:'พบ'},
    {eng:'fine',thai:'ดี'},
    {eng:'finger',thai:'นิ้ว'},
    {eng:'finish',thai:'จบ'},
    {eng:'fire',thai:'ไฟ'},
    {eng:'first',thai:'แรก'},
    {eng:'fish',thai:'ปลา'},
    {eng:'fit',thai:'พอดี'},
    {eng:'five',thai:'ห้า'},
    {eng:'flag',thai:'ธง'},
    {eng:'flat',thai:['เรียบ', 'แบน']},
    {eng:'floor',thai:'พื้น'},
    {eng:'flow',thai:'ไหล'},
    {eng:'flower',thai:'ดอกไม้'},
    {eng:'fly',thai:'บิน'},
    {eng:'follow',thai:'ติดตาม'},
    {eng:'food',thai:'อาหาร'},
    {eng:'foot',thai:'เท้า'},
    {eng:'for',thai:'สำหรับ'},
    {eng:'force',thai:['บังคับ', 'แรง']},
    {eng:'forest',thai:'ป่า'},
    {eng:'form',thai:'รูปแบบ'},
    {eng:'four',thai:'สี่'},
    {eng:'forward',thai:'ไปข้างหน้า'},
    {eng:'free',thai:['ฟรี', 'เปล่า', 'อิสระ', 'ว่าง']},
    {eng:'fresh',thai:['ใหม่', 'สดชื่น']},
    {eng:'fridge',thai:'ตู้เย็น'},
    {eng:'friend',thai:'เพื่อน'},
    {eng:'from',thai:'จาก'},
    {eng:'front',thai:'ข้างหน้า'},
    {eng:'fruit',thai:'ผลไม้'},
    {eng:'full',thai:'เต็ม'},
    {eng:'fun',thai:'สนุก'},
    {eng:'funny',thai:'ตลก'},
    {eng:'game',thai:'เกม'},
    {eng:'garden',thai:'สวน'},
    {eng:'gas',thai:'แก๊ส'},
    {eng:'gather',thai:'รวมกัน'},
    {eng:'general',thai:'ทั่วไป'},
    {eng:'gave',thai:'ให้'},
    {eng:'get',thai:'ได้รับ'},
    {eng:'girl',thai:'เด็กหญิง'},
    {eng:'give',thai:'ให้'},
    {eng:'glad',thai:'ดีใจ'},
    {eng:'glass',thai:'แก้ว'},
    {eng:'glasses',thai:'แว่นตา'},
    {eng:'go',thai:'ไป'},
    {eng:'goal',thai:'เป้าหมาย'},
    {eng:'good',thai:'ดี'},
    {eng:'got',thai:'ได้รับ'},
    {eng:'govern',thai:'ปกครอง'},
    {eng:'grand',thai:'ยิ่งใหญ่'},
    {eng:'grass',thai:'หญ้า'},
    {eng:'gray',thai:'สีเทา'},
    {eng:'great',thai:'ยิ่งใหญ่'},
    {eng:'greedy',thai:['ตะกละ', 'โลภ']},
    {eng:'green',thai:'สีเขียว'},
    {eng:'grew',thai:['ปลูก', 'โต']},
    {eng:'ground',thai:'พื้นดิน'},
    {eng:'group',thai:'กลุ่ม'},
    {eng:'grow',thai:'เติบโต'},
    {eng:'guess',thai:'เดา'},
    {eng:'guide',thai:['ไกด์', 'ไกด์นำเที่ยว', ' นำทาง']},
    {eng:'gun',thai:'ปืน'},
    {eng:'hair',thai:'ผม'},
    {eng:'half',thai:'ครึ่ง'},
    {eng:'hand',thai:'มือ'},
    {eng:'handsome',thai:'หล่อ'},
    {eng:'happen',thai:'เกิดขึ้น'},
    {eng:'happy',thai:'มีความสุข'},
    {eng:'hard',thai:['ยาก', 'แข็ง']},
    {eng:'has',thai:'มี'},
    {eng:'hat',thai:'หมวก'},
    {eng:'have',thai:'มี'},
    {eng:'he',thai:'เขา'},
    {eng:'head',thai:'หัว'},
    {eng:'healthy',thai:'มีสุขภาพดี'},
    {eng:'hear',thai:'ได้ยิน'},
    {eng:'heart',thai:'หัวใจ'},
    {eng:'heat',thai:'ความร้อน'},
    {eng:'heavy',thai:'หนัก'},
    {eng:'help',thai:'ช่วยเหลือ'},
    {eng:'her',thai:'หล่อน'},
    {eng:'hers',thai:'ของเหล่อน'},
    {eng:'here',thai:'ที่นี่'},
    {eng:'high',thai:'สูง'},
    {eng:'hill',thai:'เนินเขา'},
    {eng:'him',thai:'เขา'},
    {eng:'his',thai:'ของเขา'},
    {eng:'history',thai:'ประวัติศาสตร์'},
    {eng:'hit',thai:'ตี'},
    {eng:'hold',thai:'ถือ'},
    {eng:'hole',thai:'รู'},
    {eng:'home',thai:'บ้าน'},
    {eng:'hope',thai:['ความหวัง', 'หวัง']},
    {eng:'horse',thai:'ม้า'},
    {eng:'hospital',thai:'โรงพยาบาล'},
    {eng:'hot',thai:'ร้อน'},
    {eng:'hotel',thai:'โรงแรม'},
    {eng:'hour',thai:'ชั่วโมง'},
    {eng:'house',thai:'บ้าน'},
    {eng:'how',thai:'อย่างไร'},
    {eng:'huge',thai:'ใหญ่โต'},
    {eng:'human',thai:'คน'},
    {eng:'hundred',thai:'ร้อย'},
    {eng:'hunger',thai:'ความหิว'},
    {eng:'hunt',thai:'ล่า'},
    {eng:'hurry',thai:'รีบ'},
    {eng:'husband',thai:'สามี'},
    {eng:'I',thai:'ฉัน'},
    {eng:'ice',thai:'น้ำแข็ง'},
    {eng:'idea',thai:'ความคิด'},
    {eng:'if',thai:'ถ้า'},
    {eng:'imagine',thai:'จินตนาการ'},
    {eng:'in',thai:'ใน'},
    {eng:'in front of',thai:'ข้างหน้า'},
    {eng:'inch',thai:'นิ้ว(หน่วยวัด)'},
    {eng:'include',thai:'รวม'},
    {eng:'indicate',thai:'แสดงให้เห็น'},
    {eng:'industry',thai:'อุตสาหกรรม'},
    {eng:'insect',thai:'แมลง'},
    {eng:'instant',thai:'ทันที'},
    {eng:'instrument',thai:'เครื่องมือ'},
    {eng:'interest',thai:'ความสนใจ'},
    {eng:'interesting',thai:'น่าสนใจ'},
    {eng:'invent',thai:'ประดิษฐ์'},
    {eng:'iron',thai:'เตารีด'},
    {eng:'is',thai:['เป็น', 'อยู่', 'คือ']},
    {eng:'island',thai:'เกาะ'},
    {eng:'it',thai:'มัน'},
    {eng:'jam',thai:'แยม'},
    {eng:'job',thai:'งาน'},
    {eng:'join',thai:'เข้าร่วม'},
    {eng:'joy',thai:'ความสนุก'},
    {eng:'judge',thai:'ผู้พิพากษา'},
    {eng:'jump',thai:'กระโดด'},
    {eng:'just',thai:'เพิ่งจะ'},
    {eng:'keep',thai:'เลี้ยง'},
    {eng:'key',thai:'กุญแจ'},
    {eng:'kill',thai:'ฆ่า'},
    {eng:'kind',thai:['ใจดี', 'ชนิด']},
    {eng:'king',thai:'ราชา'},
    {eng:'know',thai:'รู้'},
    {eng:'lady',thai:'สุภาพสตรี'},
    {eng:'lake',thai:'ทะเลสาบ'},
    {eng:'land',thai:'แผ่นดิน'},
    {eng:'language',thai:'ภาษา'},
    {eng:'large',thai:'ใหญ่'},
    {eng:'last',thai:'สุดท้าย'},
    {eng:'late',thai:'สาย'},
    {eng:'laugh',thai:'หัวเราะ'},
    {eng:'law',thai:'กฎหมาย'},
    {eng:'lawyer',thai:'ทนายความ'},
    {eng:'lay',thai:'วาง'},
    {eng:'lazy',thai:'ขี้เกียจ'},
    {eng:'lead',thai:'นำ'},
    {eng:'learn',thai:'เรียนรู้'},
    {eng:'least',thai:'น้อยที่สุด'},
    {eng:'leave',thai:'ออกไป'},
    {eng:'left',thai:'ซ้าย'},
    {eng:'leg',thai:'ขา'},
    {eng:'lemon',thai:'มะนาว'},
    {eng:'length',thai:'ความยาว'},
    {eng:'less',thai:'น้อยกว่า'},
    {eng:'let',thai:'อนุญาตให้'},
    {eng:'letter',thai:'จดหมาย'},
    {eng:'level',thai:'ระดับ'},
    {eng:'lie',thai:'โกหก'},
    {eng:'life',thai:'ชีวิต'},
    {eng:'lift',thai:'ยก'},
    {eng:'light',thai:['แสงสว่าง', 'เบา']},
    {eng:'like',thai:'ชอบ'},
    {eng:'line',thai:'เส้น'},
    {eng:'liquid',thai:'ของเหลว'},
    {eng:'list',thai:'รายการ'},
    {eng:'listen',thai:'ฟัง'},
    {eng:'little',thai:'เล็ก'},
    {eng:'live',thai:'อาศัยอยู่'},
    {eng:'location',thai:'ที่ตั้ง'},
    {eng:'lone',thai:'โดดเดี่ยว'},
    {eng:'long',thai:['ยาว', 'นาน']},
    {eng:'look',thai:'มอง'},
    {eng:'loose',thai:'หลวม'},
    {eng:'lost',thai:'ทำหาย'},
    {eng:'lot',thai:'กอง'},
    {eng:'loud',thai:'ดัง'},
    {eng:'love',thai:['รัก', 'ความรัก']},
    {eng:'low',thai:'ต่ำ'},
    {eng:'lucky',thai:'โชคดี'},
    {eng:'machine',thai:'เครื่องจักร'},
    {eng:'magnet',thai:'แม่เหล็ก'},
    {eng:'main',thai:'สำคัญ'},
    {eng:'major',thai:['วิชาเอก', 'สำคัญ']},
    {eng:'make',thai:'ทำ'},
    {eng:'man',thai:'ผู้ชาย'},
    {eng:'many',thai:'มาก'},
    {eng:'map',thai:'แผนที่'},
    {eng:'mark',thai:'สัญลักษณ์'},
    {eng:'market',thai:'ตลาด'},
    {eng:'mass',thai:'มวล'},
    {eng:'match',thai:['คู่กัน', 'ไม้ขีด']},
    {eng:'material',thai:'วัสดุ'},
    {eng:'matter',thai:'วัตถุ'},
    {eng:'may',thai:'อาจจะ'},
    {eng:'me',thai:'ฉัน'},
    {eng:'mean',thai:'หมายถึง'},
    {eng:'meat',thai:'เนื้อ'},
    {eng:'meet',thai:'พบ'},
    {eng:'men',thai:'ผู้ชายหลายคน'},
    {eng:'metal',thai:'เหล็ก'},
    {eng:'method',thai:'วิธีการ'},
    {eng:'middle',thai:'กลาง'},
    {eng:'might',thai:'พลัง'},
    {eng:'mile',thai:'ไมล์'},
    {eng:'milk',thai:'นม'},
    {eng:'million',thai:'ล้าน'},
    {eng:'mind',thai:'อ่อนโยน'},
    {eng:'mine',thai:'ของฉัน'},
    {eng:'minute',thai:'นาที'},
    {eng:'miss',thai:'นางสาว'},
    {eng:'mix',thai:'ผสม'},
    {eng:'modern',thai:'สมัยใหม่'},
    {eng:'moment',thai:'ช่วงขณะ'},
    {eng:'money',thai:'เงิน'},
    {eng:'monkey',thai:'ลิง'},
    {eng:'month',thai:'เดือน'},
    {eng:'moon',thai:'พระจันทร์'},
    {eng:'more',thai:['มากว่า', 'อีก']},
    {eng:'morning',thai:'ตอนเช้า'},
    {eng:'most',thai:'ที่สุด'},
    {eng:'mother',thai:'แม่'},
    {eng:'motion',thai:'การเคลื่อนไหว'},
    {eng:'mountain',thai:'ภูเขา'},
    {eng:'mouse',thai:'หนู'},
    {eng:'mouth',thai:'ปาก'},
    {eng:'move',thai:'คลื่อนไหว'},
    {eng:'much',thai:'มาก'},
    {eng:'music',thai:'ดนตรี'},
    {eng:'must',thai:'ต้อง'},
    {eng:'my',thai:'ของฉัน'},
    {eng:'name',thai:'ชื่อ'},
    {eng:'narrow',thai:'แคบ'},
    {eng:'nation',thai:'ชาติ'},
    {eng:'natural',thai:'จากธรรมชาติ'},
    {eng:'nature',thai:'ธรรมชาติ'},
    {eng:'near',thai:'ใกล้'},
    {eng:'necessary',thai:'จำเป็น'},
    {eng:'neck',thai:'คอ'},
    {eng:'need',thai:'ต้องการ'},
    {eng:'neighbor',thai:'เพื่อนบ้าน'},
    {eng:'never',thai:'ไม่เคย'},
    {eng:'new',thai:'ใหม่'},
    {eng:'next',thai:'ถัดไป'},
    {eng:'night',thai:'กลางคืน'},
    {eng:'nine',thai:'เก้า'},
    {eng:'no',thai:'ไม่'},
    {eng:'noise',thai:'เสียง'},
    {eng:'noisy',thai:'เสียงดัง'},
    {eng:'noon',thai:'เที่ยง'},
    {eng:'north',thai:'ทิศเหนือ'},
    {eng:'nose',thai:'จมูก'},
    {eng:'note',thai:'โน้ต'},
    {eng:'notebook',thai:'สมุด'},
    {eng:'notice',thai:'ประกาศ'},
    {eng:'nothing',thai:'ไม่มีอะไร'},
    {eng:'now',thai:'ขณะนี้'},
    {eng:'number',thai:'หมายเลข'},
    {eng:'nurse',thai:'พยาบาล'},
    {eng:'object',thai:['วัตถุ', 'วัตถุประสงค์']},
    {eng:'observe',thai:'สังเกต'},
    {eng:'ocean',thai:'มหาสมุทร'},
    {eng:'of',thai:'ของ'},
    {eng:'off',thai:['ไกล', 'ปิด']},
    {eng:'offer',thai:'ยื่นข้อเสนอ'},
    {eng:'office',thai:'สำนักงาน'},
    {eng:'often',thai:'บ่อยๆ'},
    {eng:'oil',thai:'น้ำมัน'},
    {eng:'old',thai:['เก่า', 'แก่']},
    {eng:'on',thai:'บน'},
    {eng:'once',thai:'ครั้งหนึ่ง'},
    {eng:'one',thai:'หนึ่ง'},
    {eng:'only',thai:'เท่านั้น'},
    {eng:'open',thai:'เปิด'},
    {eng:'opposite',thai:'ตรงข้าม'},
    {eng:'or',thai:'หรือ'},
    {eng:'orange',thai:['ส้ม', 'สีส้ม']},
    {eng:'order',thai:'สั่ง'},
    {eng:'organ',thai:'อวัยวะ'},
    {eng:'original',thai:'ดั้งเดิม'},
    {eng:'other',thai:'อื่น'},
    {eng:'our',thai:'ของพวกเรา'},
    {eng:'ours',thai:'ของพวกเรา'},
    {eng:'out',thai:'นอก'},
    {eng:'over',thai:'เหนือ'},
    {eng:'own',thai:'เป็นเจ้าของ'},
    {eng:'oxygen',thai:'ออกซิเจน'},
    {eng:'page',thai:'หน้า'},
    {eng:'paint',thai:'ทาสี'},
    {eng:'pair',thai:'คู่'},
    {eng:'pants',thai:'การเกงขายาว'},
    {eng:'paper',thai:'กระดาษ'},
    {eng:'paragraph',thai:'ย่อหน้า'},
    {eng:'parents',thai:'พ่อแม่'},
    {eng:'part',thai:'ส่วน'},
    {eng:'particular',thai:'เฉพาะ'},
    {eng:'party',thai:'ปาร์ตี้'},
    {eng:'pass',thai:'ผ่าน'},
    {eng:'past',thai:'อดีต'},
    {eng:'path',thai:'ทาง'},
    {eng:'patient',thai:['อดทน', 'คนไข้']},
    {eng:'pay',thai:'จ่าย'},
    {eng:'pen',thai:'ปากกา'},
    {eng:'pencil',thai:'ดินสอ'},
    {eng:'people',thai:'ผู้คน'},
    {eng:'perhaps',thai:'บางที'},
    {eng:'period',thai:'ช่วงเวลา'},
    {eng:'person',thai:'บุคคล'},
    {eng:'phrase',thai:'วลี'},
    {eng:'pick',thai:'เก็บ'},
    {eng:'picture',thai:'ภาพ'},
    {eng:'piece',thai:'ชิ้น'},
    {eng:'pig',thai:'หมู'},
    {eng:'pizza',thai:'พิซซ่า'},
    {eng:'place',thai:'สถานที่'},
    {eng:'plain',thai:['เรียบ', 'ธรรมดา']},
    {eng:'plan',thai:'แผนการ'},
    {eng:'plane',thai:'เครื่องบิน'},
    {eng:'planet',thai:'ดาวเคราะห์'},
    {eng:'plant',thai:['พืช', 'โรงงาน']},
    {eng:'play',thai:'เล่น'},
    {eng:'please',thai:'กรุณา'},
    {eng:'poem',thai:'กลอน'},
    {eng:'point',thai:'คะแนน'},
    {eng:'policeman',thai:'ตำรวจ'},
    {eng:'poor',thai:'จน'},
    {eng:'popular',thai:'เป็นที่นิยม'},
    {eng:'port',thai:'ท่าเรือ'},
    {eng:'position',thai:'ตำแหน่ง(การงาน)'},
    {eng:'possible',thai:'เป็นไปได้'},
    {eng:'post',thai:'พัสดุไปรษณี'},
    {eng:'postman',thai:'บุรุษไปรษณีย์'},
    {eng:'pound',thai:'ปอนด์'},
    {eng:'power',thai:'พลัง'},
    {eng:'practice',thai:'ฝึกฝน'},
    {eng:'prepare',thai:'เตรียม'},
    {eng:'present',thai:'ของขวัญ'},
    {eng:'press',thai:'กด'},
    {eng:'pretty',thai:'เก๋ไก๋'},
    {eng:'print',thai:'พิมพ์'},
    {eng:'problem',thai:'ปัญหา'},
    {eng:'process',thai:'กระบวนการ'},
    {eng:'produce',thai:'ผลิต'},
    {eng:'product',thai:'ผลิตภัณฑ์'},
    {eng:'proper',thai:'เหมาะสม'},
    {eng:'property',thai:'ทรัพย์สมบัติ'},
    {eng:'protect',thai:'ปกป้อง'},
    {eng:'prove',thai:'พิสูจน์'},
    {eng:'provide',thai:'ให้'},
    {eng:'pull',thai:'ดึง'},
    {eng:'push',thai:'ผลัก'},
    {eng:'put',thai:'วาง'},
    {eng:'question',thai:'คำถาม'},
    {eng:'quick',thai:'เร็ว'},
    {eng:'quiet',thai:'เงียบ'},
    {eng:'quite',thai:'ค่อนข้าง'},
    {eng:'race',thai:'การแข่งขัน'},
    {eng:'radio',thai:'วิทยุ'},
    {eng:'rail',thai:'ราง'},
    {eng:'rain',thai:'ฝน'},
    {eng:'raise',thai:'ยก'},
    {eng:'range',thai:'แนว'},
    {eng:'rather',thai:['ค่อนข้าง', 'มากกว่า']},
    {eng:'reach',thai:'เอื้อม'},
    {eng:'read',thai:'อ่าน'},
    {eng:'ready',thai:'พร้อม'},
    {eng:'real',thai:'จริง'},
    {eng:'reason',thai:'เหตุผล'},
    {eng:'receive',thai:'ได้รับ'},
    {eng:'record',thai:'บันทึก'},
    {eng:'red',thai:'สีแดง'},
    {eng:'region',thai:'ภูมิภาค'},
    {eng:'remember',thai:'จดจำ'},
    {eng:'repeat',thai:'ทำซ้ำ'},
    {eng:'reply',thai:'ตอบ'},
    {eng:'represent',thai:'เป็นตัวแทน'},
    {eng:'require',thai:['จำเป็นต้อง', 'ต้องการ']},
    {eng:'rest',thai:'พัก'},
    {eng:'result',thai:'ผล'},
    {eng:'rice',thai:'ข้าว'},
    {eng:'rich',thai:'รวย'},
    {eng:'ride',thai:'ขี่'},
    {eng:'right',thai:'ถูกต้อง'},
    {eng:'ring',thai:'สั่น'},
    {eng:'river',thai:'แม่น้ำ'},
    {eng:'road',thai:'ถนน'},
    {eng:'rock',thai:'หิน'},
    {eng:'roll',thai:'ม้วน'},
    {eng:'room',thai:'ห้อง'},
    {eng:'root',thai:'ราก'},
    {eng:'rope',thai:'เชือก'},
    {eng:'rose',thai:'กุหลาบ'},
    {eng:'round',thai:'กลม'},
    {eng:'row',thai:'แถว'},
    {eng:'rub',thai:'ถู'},
    {eng:'rule',thai:'ปกครอง'},
    {eng:'run',thai:'วิ่ง'},
    {eng:'sad',thai:'เศร้า'},
    {eng:'safe',thai:'ปลอดภัย'},
    {eng:'sail',thai:'ล่องเรือ'},
    {eng:'salt',thai:'เกลือ'},
    {eng:'same',thai:'เหมือนกัน'},
    {eng:'save',thai:['ช่วยชีวิต', 'บันทึก']},
    {eng:'say',thai:'พูด'},
    {eng:'scale',thai:'ตาชั่ง'},
    {eng:'school',thai:'โรงเรียน'},
    {eng:'science',thai:'วิทยาศาสตร์'},
    {eng:'score',thai:'คะแนน'},
    {eng:'sea',thai:'ทะเล'},
    {eng:'search',thai:'ค้นหา'},
    {eng:'season',thai:'ฤดู'},
    {eng:'seat',thai:'ที่นั่ง'},
    {eng:'second',thai:'ที่สอง'},
    {eng:'section',thai:'แผนก'},
    {eng:'see',thai:'เห็น'},
    {eng:'seed',thai:'เมล็ด'},
    {eng:'seem',thai:'ดูเหมือน'},
    {eng:'select',thai:'เลือก'},
    {eng:'self',thai:'เอง'},
    {eng:'sell',thai:'ขาย'},
    {eng:'send',thai:'ส่ง'},
    {eng:'sense',thai:'ประสาทสัมผัสทั้งห้า'},
    {eng:'sentence',thai:'ประโยค'},
    {eng:'separate',thai:'แยกกัน'},
    {eng:'serve',thai:'บริการ'},
    {eng:'set',thai:'จัด'},
    {eng:'settle',thai:'ตั้งรกราก'},
    {eng:'seven',thai:'เจ็ด'},
    {eng:'several',thai:'หลาย'},
    {eng:'shall',thai:'จะ'},
    {eng:'shallow',thai:'ตื้น'},
    {eng:'shape',thai:'รูปร่าง'},
    {eng:'share',thai:'แบ่งปัน'},
    {eng:'sharp',thai:['คม', 'แหลม']},
    {eng:'she',thai:'หล่อน'},
    {eng:'sheep',thai:'แกะ'},
    {eng:'sheet',thai:'แผ่น'},
    {eng:'shell',thai:'หอย'},
    {eng:'shine',thai:'ส่องแสง'},
    {eng:'ship',thai:'เรือใหญ่'},
    {eng:'shirt',thai:'เสื้อเชิ๊ต'},
    {eng:'shoe',thai:'รองเท้า'},
    {eng:'shop',thai:'ร้านค้า'},
    {eng:'shore',thai:'ฝั่ง'},
    {eng:'short',thai:['สั้น', 'เตี้ย']},
    {eng:'should',thai:'ควรจะ'},
    {eng:'shoulder',thai:'บ่า'},
    {eng:'shout',thai:'ตะโกน'},
    {eng:'show',thai:'แสดง'},
    {eng:'side',thai:'ด้าน'},
    {eng:'sight',thai:'การมองเห็น'},
    {eng:'sign',thai:'สัญลักษณ์'},
    {eng:'single',thai:'โสด'},
    {eng:'sister',thai:['พี่สาว', 'น้องสาว']},
    {eng:'sit',thai:'นั่ง'},
    {eng:'six',thai:'หก'},
    {eng:'size',thai:'ขนาด'},
    {eng:'skill',thai:'ทักษะ'},
    {eng:'skin',thai:'ผิวหนัง'},
    {eng:'skirt',thai:'กระโปรง'},
    {eng:'sky',thai:'ท้องฟ้า'},
    {eng:'sleep',thai:'นอน'},
    {eng:'slip',thai:'ลื่น'},
    {eng:'slow',thai:'ช้า'},
    {eng:'small',thai:'เล็ก'},
    {eng:'smell',thai:'ดม'},
    {eng:'smile',thai:'ยิ้ม'},
    {eng:'snow',thai:'หิมะ'},
    {eng:'so',thai:'ดังนั้น'},
    {eng:'sock',thai:'ถุงเท้า'},
    {eng:'soft',thai:'นุ่ม'},
    {eng:'soil',thai:'ดิน'},
    {eng:'soldier',thai:'ทหาร'},
    {eng:'solution',thai:'ทางแก้ปัญหา'},
    {eng:'solve',thai:'แก้ปัญหา'},
    {eng:'some',thai:['บางคน', 'บางอัน', 'บางตัว']},
    {eng:'son',thai:'ลูกชาย'},
    {eng:'song',thai:'เพลง'},
    {eng:'soon',thai:'ในไม่ช้า'},
    {eng:'sorry',thai:'เสียใจ'},
    {eng:'sound',thai:'เสียง'},
    {eng:'south',thai:'ทิศใต้'},
    {eng:'space',thai:['อวกาศ', 'พื้นที่']},
    {eng:'speak',thai:'พูด'},
    {eng:'special',thai:'พิเศษ'},
    {eng:'speech',thai:'คำพูด'},
    {eng:'speed',thai:'ความเร็ว'},
    {eng:'spell',thai:'สะกด'},
    {eng:'spend',thai:['ใช้', 'ใช้เวลา', 'ใช้เงิน']},
    {eng:'sport',thai:'กีฬา'},
    {eng:'spot',thai:'จุด'},
    {eng:'spread',thai:'ขยาย'},
    {eng:'spring',thai:'ฤดูใบไม้ผลิ'},
    {eng:'square',thai:'จัตุรัส'},
    {eng:'stand',thai:'ยืน'},
    {eng:'star',thai:'ดาว'},
    {eng:'start',thai:'เริ่ม'},
    {eng:'state',thai:'รํฐ'},
    {eng:'station',thai:'สถานี'},
    {eng:'stay',thai:'พัก'},
    {eng:'steam',thai:'ไอน้ำ'},
    {eng:'step',thai:'ก้าว'},
    {eng:'stick',thai:'ติด'},
    {eng:'still',thai:['ยังคง', 'นิ่ง']},
    {eng:'stone',thai:'หิน'},
    {eng:'stop',thai:'หยุด'},
    {eng:'store',thai:'ร้านค้า'},
    {eng:'story',thai:'เรื่องราว'},
    {eng:'straight',thai:'ตรง'},
    {eng:'strange',thai:'แปลก'},
    {eng:'stream',thai:'ลำธาร'},
    {eng:'street',thai:'ถนน'},
    {eng:'stretch',thai:'ยืดขยาย'},
    {eng:'strike',thai:['ตี', 'ประท้วง']},
    {eng:'string',thai:'เชือก'},
    {eng:'strong',thai:'แข็งแรง'},
    {eng:'student',thai:'นักเรียน'},
    {eng:'stupid',thai:'โง่'},
    {eng:'subject',thai:['วิชา', 'หัวข้อ']},
    {eng:'substance',thai:'สาร'},
    {eng:'succeed',thai:'สำเร็จ'},
    {eng:'success',thai:'ความสำเร็จ'},
    {eng:'such',thai:'เช่นนั้น'},
    {eng:'sudden',thai:'ทันที'},
    {eng:'sugar',thai:'น้ำตาล'},
    {eng:'suggest',thai:'แนะนำ'},
    {eng:'suit',thai:'ชุดสูท'},
    {eng:'summer',thai:'ฤดูร้อน'},
    {eng:'sun',thai:'พระอาทิตย์'},
    {eng:'supply',thai:'แจกจ่าย'},
    {eng:'support',thai:'สนับสนุน'},
    {eng:'sure',thai:'มั่นใจ'},
    {eng:'surface',thai:'พื้นผิว'},
    {eng:'surprise',thai:'ความแปลกใจ'},
    {eng:'sweet',thai:'หวาน'},
    {eng:'swim',thai:'ว่ายน้ำ'},
    {eng:'symbol',thai:'สัญลักษณ์'},
    {eng:'system',thai:'ระบบ'},
    {eng:'table',thai:'โต๊ะ'},
    {eng:'tail',thai:'หาง'},
    {eng:'take',thai:'เอา'},
    {eng:'talk',thai:'สนทนา'},
    {eng:'tall',thai:'สูง'},
    {eng:'tea',thai:'ชา'},
    {eng:'teach',thai:'สอน'},
    {eng:'teacher',thai:'ครู'},
    {eng:'team',thai:'ทีม'},
    {eng:'tell',thai:'บอก'},
    {eng:'temperature',thai:'อุณหภูมิ'},
    {eng:'ten',thai:'สิบ'},
    {eng:'term',thai:'ระยะเวลา'},
    {eng:'test',thai:'การทดสอบ'},
    {eng:'than',thai:'กว่า'},
    {eng:'thank',thai:'ขอบคุณ'},
    {eng:'that',thai:['นั่น', 'ที่', 'ว่า']},
    {eng:'theatre ',thai:['ภาพยนตร์', 'โรงภาพยนตร์ ']},
    {eng:'their',thai:'ของพวกเขา'},
    {eng:'theirs',thai:'ของพวกเขา'},
    {eng:'them',thai:'พวกเขา'},
    {eng:'then',thai:'ต่อมา'},
    {eng:'there',thai:'ที่นั่น'},
    {eng:'these',thai:'เหล่านี้'},
    {eng:'they',thai:'พวกเขา'},
    {eng:'thick',thai:'หนา'},
    {eng:'thin',thai:['ผอม', 'บาง']},
    {eng:'thing',thai:'สิ่งของ'},
    {eng:'think',thai:'คิด'},
    {eng:'third',thai:'ลำดับที่สาม'},
    {eng:'this',thai:'นี่'},
    {eng:'those',thai:'เหล่านั้น'},
    {eng:'though',thai:'แม้ว่า'},
    {eng:'thought',thai:'ความคิด'},
    {eng:'threaten',thai:'ข่มขู่'},
    {eng:'thousand',thai:'พัน'},
    {eng:'three',thai:'สาม'},
    {eng:'through',thai:['ผ่าน', 'ตลอด']},
    {eng:'throw',thai:'ขว้าง'},
    {eng:'tired',thai:['เหนื่อย', 'เมื่อย']},
    {eng:'tight',thai:'แน่น'},
    {eng:'time',thai:'เวลา'},
    {eng:'tiny',thai:'เล็ก'},
    {eng:'tire',thai:'ยาง'},
    {eng:'to',thai:['สู่', 'ถึง']},
    {eng:'today',thai:'วันนี้'},
    {eng:'together',thai:'ด้วยกัน'},
    {eng:'tomato',thai:'มะเขือเทศ'},
    {eng:'tomorrow',thai:'พรุ่งนี้'},
    {eng:'tonight',thai:'คืนนี้'},
    {eng:'too',thai:'เช่นกัน'},
    {eng:'tool',thai:'เครื่องมือ'},
    {eng:'tooth',thai:'ฟัน'},
    {eng:'top',thai:'ยอด'},
    {eng:'total',thai:'ทั้งหมด'},
    {eng:'touch',thai:'สัมผัส'},
    {eng:'toward',thai:'ไปยัง'},
    {eng:'town',thai:'เมือง'},
    {eng:'track',thai:'ทางเดิน'},
    {eng:'trade',thai:'การค้า'},
    {eng:'train',thai:'รถไฟ'},
    {eng:'travel',thai:'เดินทาง'},
    {eng:'tree',thai:'ต้นไม้'},
    {eng:'trip',thai:'การเดินทาง'},
    {eng:'trouble',thai:'อุปสรรค'},
    {eng:'truck',thai:'รถบรรทุก'},
    {eng:'true',thai:'จริง'},
    {eng:'try',thai:['พยายาม', 'ลอง']},
    {eng:'twenty',thai:'ยี่สิบ'},
    {eng:'two',thai:'สอง'},
    {eng:'type',thai:'ชนิด'},
    {eng:'uncle',thai:'ลุง'},
    {eng:'under',thai:'ใต้'},
    {eng:'understand',thai:'เข้าใจ'},
    {eng:'unit',thai:'หน่วย'},
    {eng:'until',thai:'จนกระทั่ง'},
    {eng:'up',thai:'บน'},
    {eng:'us',thai:'พวกเรา'},
    {eng:'use',thai:'ใช้'},
    {eng:'usual',thai:'ปกติ'},
    {eng:'valley',thai:'หุบเขา'},
    {eng:'value',thai:'มูลค่า'},
    {eng:'vary',thai:'แตกต่าง'},
    {eng:'view',thai:'มุมมอง'},
    {eng:'village',thai:'วิ๊ลลิจ	หมู่บ้าน'},
    {eng:'visit',thai:['เยี่ยม', 'เยี่ยมชม']},
    {eng:'voice',thai:'เสียง'},
    {eng:'walk',thai:'เดิน'},
    {eng:'wall',thai:'กำแพง'},
    {eng:'want',thai:'ต้องการ'},
    {eng:'war',thai:'สงคราม'},
    {eng:'warm',thai:'อุ่น'},
    {eng:'warn',thai:'เตือน'},
    {eng:'wash',thai:['ซัก', 'ล้าง']},
    {eng:'watch',thai:'ดู'},
    {eng:'water',thai:'น้ำ'},
    {eng:'wave',thai:['คลื่น', 'โบกมือ']},
    {eng:'way',thai:['ทาง', 'หนทาง']},
    {eng:'we',thai:'พวกเรา'},
    {eng:'weak',thai:'อ่อนแอ'},
    {eng:'wear',thai:'สวมใส่'},
    {eng:'weather',thai:'สภาพอากาศ'},
    {eng:'week',thai:'สัปดาห์'},
    {eng:'weigh',thai:'มีน้ำหนัก'},
    {eng:'weight',thai:'น้ำหนัก'},
    {eng:'well',thai:['ดี', 'อ้อ']},
    {eng:'west',thai:'ทิศตะวันตก'},
    {eng:'wet',thai:'เปียก'},
    {eng:'what',thai:['อะไร', 'สิ่งที่']},
    {eng:'wheel',thai:'ล้อ'},
    {eng:'when',thai:['เมื่อ', 'เมื่อไหร่']},
    {eng:'where',thai:['ที่ไหน', 'สถานที่ซึ่ง']},
    {eng:'whether',thai:['ว่า', 'ไม่ว่า']},
    {eng:'which',thai:['อันไหน', 'ที่']},
    {eng:'while',thai:'ขณะที่'},
    {eng:'white',thai:'สีขาว'},
    {eng:'who',thai:['ใคร', 'ผู้ที่']},
    {eng:'whole',thai:'ทั้งหมด'},
    {eng:'whose',thai:'ของใค'},
    {eng:'why',thai:['ทำไม', 'เหตุผลที่']},
    {eng:'wide',thai:'กว้าง'},
    {eng:'wife',thai:'ภรรยา'},
    {eng:'wild',thai:'จากป่า'},
    {eng:'will',thai:'จะ'},
    {eng:'win',thai:'ชนะ'},
    {eng:'wind',thai:'ลม'},
    {eng:'wine',thai:'ไวน์'},
    {eng:'window',thai:'หน้าต่าง'},
    {eng:'wing',thai:'ปีก'},
    {eng:'winter',thai:'ฤดูหนาว'},
    {eng:'wire',thai:'ลวด'},
    {eng:'wish',thai:'ปรารถนา'},
    {eng:'with',thai:'กับ'},
    {eng:'woman',thai:'ผู้หญิง'},
    {eng:'wonder',thai:'แปลกใจ'},
    {eng:'wood',thai:'ไม้'},
    {eng:'word',thai:'คำ'},
    {eng:'work',thai:['งาน', 'ทำงาน']},
    {eng:'world',thai:'โลก'},
    {eng:'worse',thai:'เลวกว่า'},
    {eng:'would',thai:'จะ'},
    {eng:'write',thai:'เขียน'},
    {eng:'wrong',thai:'ผิด'},
    {eng:'yard',thai:'หลา'},
    {eng:'year',thai:'ปี'},
    {eng:'yellow',thai:'สีเหลือง'},
    {eng:'yes',thai:'ใช่'},
    {eng:'yesterday',thai:'เมื่อวาน'},
    {eng:'you',thai:'คุณ'},
    {eng:'young',thai:['เด็ก', 'เป็นวัยรุ่น']},
    {eng:'your',thai:'ของคุณ'},
    {eng:'yours',thai:'ของคุณ'},
    {eng:'zebra',thai:'ม้าลาย'},
    {eng:'zero',thai:'ศูนย์'},
    {eng:'zoo',thai:'สวนสัตว์'},
]



// เซ็ตค่าเริ่มต้น
show.innerHTML = data[0].thai
let Rank = 0 
const typeSring = typeof(data[1].thai)
const typeArray = typeof(data[2].thai)

function checkEN(){
    
    if(input.value === data[Rank].eng){
        Rank += 1

        if(Rank > max ){Rank = min}

        anser.innerHTML = 'True'
        anser.style.color = 'green'
        setTimeout(() => {
            if(typeof(data[Rank].thai) === typeArray){
                show.innerHTML= data[Rank].thai[0]
            }else{
                show.innerHTML= data[Rank].thai
            }
            anser.innerHTML = ''
            input.value = ''
            Ranking.innerHTML = `Rank : ${Rank}`
        }, 1000);

    }else{
        anser.style.color = 'red'
        anser.innerHTML = data[Rank].eng
        input.value = ''
        setTimeout(()=>{
            anser.innerHTML = ''
        },5000)
    }
}



function checkTH(){
    if(input.value === data[Rank].thai || data[Rank].thai.includes(input.value)){
        Rank += 1

        if(Rank > max){Rank = min}

        anser.innerHTML = 'True'
        anser.style.color = 'green'
        setTimeout(() => {
            show.innerHTML= data[Rank].eng
            anser.innerHTML = ''
            input.value = ''
            Ranking.innerHTML = `Rank : ${Rank}`
        }, 1000);

    }else{
        anser.style.color = 'red'
        anser.innerHTML = data[Rank].thai
        input.value = ''
        setTimeout(()=>{
            anser.innerHTML = ''
        },5000)
    }
}


let mode_lve_nal = 0
//mode nal 0
//mode lve 1
// function modeAll(){
//     if(mode_lve_nal === 0){
//         if(Rank === data.length){Rank = 0}
//     }else{
//         if(Rank === mex){Rank = 0}
//     }
// }


let setmode = 0
function checkMode(){
    if(setmode === 0){
        checkEN()
    }else{
        checkTH()
    }
}


let LevelBt = ''
for(let i = 1;i<=data.length/5;i++){
    LevelBt += `<button class="item_bt" > Level : ${i} </button>`
}
tabLevel.innerHTML = LevelBt

const Level = document.querySelectorAll('.item_bt')

let min
let max
Level.forEach((e,i)=>{
    e.addEventListener('click',()=>{
        Level.forEach((item,i)=>{
            item.style.background = "#f0f0f0"
            item.style.border = "1px solid black"
            
        })
        e.style.background = '#7aff88'
        
        mode_lve_nal = 1
        
        min = i*5; 
        max = min+4;
        Rank = min
        Ranking.innerHTML = `Rank : ${Rank}`
        if(setmode === 0){
            // show.innerHTML= data[Rank].thai
            if(typeof(data[Rank].thai) === typeArray){
                show.innerHTML= data[Rank].thai[0]
            }else{
                show.innerHTML= data[Rank].thai
            }
        }else{
            show.innerHTML= data[Rank].eng
        }
        
    })
})
//index 1
//min 1*5 =5
//max 5+4 = 9












modeEN.addEventListener('click',()=>{
    modeEN.style.background = 'red'
    modeEN.style.color = 'aliceblue'
    modeTH.style.background = 'none'
    modeTH.style.color = 'black'
    if(setmode === 1){
        setmode = 0
    }
    show.innerHTML= data[Rank].thai
})

modeTH.addEventListener('click',()=>{
    modeTH.style.background = 'red'
    modeTH.style.color = 'aliceblue'
    modeEN.style.background = 'none'
    modeEN.style.color = 'black'
    if(setmode === 0){
        setmode = 1
    }
    show.innerHTML= data[Rank].eng
})
submit.addEventListener('click',()=>{
    checkMode()
})
// on enter 
// "keypress" = เมื่อคีย์ข้อมูลใน input จะทำงานฟังชั่น
input.addEventListener("keypress", function(event) {
    if (event.key === "Enter") {
        checkMode()
    }
  });